name: Test

on:
  - pull_request
  - push

jobs:
  test-jekyll-geolexica:
    name: Jekyll ${{ matrix.jekyll }} on Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        jekyll: [ "4.0", "4.1", "4.2" ]
        ruby: [ "2.7", "3.0" ]

    env:
      BUNDLE_GEMFILE: gemfiles/Jekyll-${{ matrix.jekyll }}.gemfile

    steps:
      - uses: actions/checkout@v2
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rspec
